industries_map = {
    "Information Technology (IT)": "information_technology",
    "Finance and Banking": "finance_and_banking",
    "Healthcare": "healthcare",
    "Education": "education",
    "Telecommunications": "telecommunications",
    "Retail and E-commerce": "retail_and_ecommerce",
    "Manufacturing": "manufacturing",
    "Energy and Utilities": "energy_and_utilities",
    "Government and Public Sector": "government_and_public_sector",
    "Logistics and Supply Chain": "logistics_and_supply_chain",
    "Media and Entertainment": "media_and_entertainment",
    "Travel and Hospitality": "travel_and_hospitality",
    "Real Estate": "real_estate",
    "Consulting": "consulting",
    "Automotive": "automotive",
    "Aerospace": "aerospace",
    "Pharmaceuticals": "pharmaceuticals",
    "Agriculture": "agriculture",
    "Construction": "construction",
    "Insurance": "insurance"
}

rev_industries_map = {
    "information_technology": "Information Technology (IT)",
    "finance_and_banking": "Finance and Banking",
    "healthcare": "Healthcare",
    "education": "Education",
    "telecommunications": "Telecommunications",
    "retail_and_ecommerce": "Retail and E-commerce",
    "manufacturing": "Manufacturing",
    "energy_and_utilities": "Energy and Utilities",
    "government_and_public_sector": "Government and Public Sector",
    "logistics_and_supply_chain": "Logistics and Supply Chain",
    "media_and_entertainment": "Media and Entertainment",
    "travel_and_hospitality": "Travel and Hospitality",
    "real_estate": "Real Estate",
    "consulting": "Consulting",
    "automotive": "Automotive",
    "aerospace": "Aerospace",
    "pharmaceuticals": "Pharmaceuticals",
    "agriculture": "Agriculture",
    "construction": "Construction",
    "insurance": "Insurance"
}

job_domains = [
    "Software Development",
    "Data Science and Analytics",
    "Cybersecurity",
    "Cloud Computing",
    "Artificial Intelligence (AI) & Machine Learning (ML)",
    "Business Analytics",
    "Project Management",
    "Sales and Marketing",
    "Human Resources (HR)",
    "Operations Management",
    "Product Management",
    "Finance and Accounting",
    "Research and Development (R&D)",
    "Customer Support",
    "DevOps",
    "Network Engineering",
    "UI/UX Design",
    "Legal and Compliance",
    "Digital Marketing",
    "Quality Assurance (QA)"
]
